package com.converter.generator;

import com.converter.model.*;
import com.converter.model.JavaClass.JavaField;
import com.converter.model.JavaClass.JavaMethod;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates Java source code from a COBOL program model.
 */
public class JavaCodeGenerator {
    private static final Logger logger = LoggerFactory.getLogger(JavaCodeGenerator.class);
    
    /**
     * Generate a Java class from a COBOL program.
     */
    public JavaClass generate(CobolProgram cobolProgram) {
        logger.info("Generating Java code for program: {}", cobolProgram.getProgramId());
        
        // Create Java class with converted name
        String className = convertToJavaClassName(cobolProgram.getProgramId());
        JavaClass javaClass = new JavaClass(className);
        
        // Add necessary imports
        addImports(javaClass);
        
        // Convert data items to fields
        convertDataItems(cobolProgram, javaClass);
        
        // Convert paragraphs to methods
        convertParagraphs(cobolProgram, javaClass);
        
        // Add main method
        addMainMethod(javaClass);
        
        logger.info("Java code generation completed for class: {}", className);
        return javaClass;
    }
    
    /**
     * Write the Java class to a file.
     */
    public void writeToFile(JavaClass javaClass, Path outputDir) throws IOException {
        String fileName = javaClass.getClassName() + ".java";
        Path filePath = outputDir.resolve(fileName);
        
        StringBuilder sb = new StringBuilder();
        
        // Package declaration (if any)
        if (javaClass.getPackageName() != null) {
            sb.append("package ").append(javaClass.getPackageName()).append(";\n\n");
        }
        
        // Imports
        for (String importStmt : javaClass.getImports()) {
            sb.append("import ").append(importStmt).append(";\n");
        }
        if (!javaClass.getImports().isEmpty()) {
            sb.append("\n");
        }
        
        // Class declaration
        sb.append("/**\n");
        sb.append(" * Generated from COBOL program\n");
        sb.append(" * Auto-generated by COBOL-to-Java Converter\n");
        sb.append(" */\n");
        sb.append("public class ").append(javaClass.getClassName()).append(" {\n\n");
        
        // Fields
        for (JavaField field : javaClass.getFields()) {
            sb.append("    ").append(field.getVisibility()).append(" ");
            sb.append(field.getType()).append(" ").append(field.getName());
            if (field.getInitialValue() != null) {
                sb.append(" = ").append(field.getInitialValue());
            }
            sb.append(";\n");
        }
        sb.append("\n");
        
        // Methods
        for (JavaMethod method : javaClass.getMethods()) {
            sb.append("    ").append(method.getVisibility()).append(" ");
            sb.append(method.getReturnType()).append(" ").append(method.getName()).append("(");
            
            // Parameters
            for (int i = 0; i < method.getParameters().size(); i++) {
                sb.append(method.getParameters().get(i));
                if (i < method.getParameters().size() - 1) {
                    sb.append(", ");
                }
            }
            sb.append(") {\n");
            
            // Method body
            for (String line : method.getBody()) {
                sb.append("        ").append(line).append("\n");
            }
            
            sb.append("    }\n\n");
        }
        
        sb.append("}\n");
        
        // Write to file
        Files.writeString(filePath, sb.toString());
        logger.info("Java file written to: {}", filePath);
    }
    
    private void addImports(JavaClass javaClass) {
        javaClass.addImport("java.math.BigDecimal");
        javaClass.addImport("java.io.*");
    }
    
    private void convertDataItems(CobolProgram cobolProgram, JavaClass javaClass) {
        logger.debug("Converting data items to Java fields...");
        
        for (DataItem item : cobolProgram.getWorkingStorageSection()) {
            // Only convert level 01 items (top-level variables)
            if (item.getLevel() == 1) {
                JavaField field = new JavaField(
                    convertToJavaFieldName(item.getName()),
                    mapCobolTypeToJava(item)
                );
                
                if (item.getValue() != null) {
                    field.setInitialValue(formatJavaValue(item));
                }
                
                javaClass.addField(field);
                logger.debug("Converted field: {} -> {} {}", 
                    item.getName(), field.getType(), field.getName());
            }
        }
    }
    
    private void convertParagraphs(CobolProgram cobolProgram, JavaClass javaClass) {
        logger.debug("Converting paragraphs to Java methods...");
        
        for (Paragraph paragraph : cobolProgram.getParagraphs()) {
            JavaMethod method = new JavaMethod(
                convertToJavaMethodName(paragraph.getName()),
                "void"
            );
            
            // Convert statements to Java code
            for (Statement statement : paragraph.getStatements()) {
                String javaCode = convertStatement(statement);
                if (javaCode != null) {
                    method.addBodyLine(javaCode);
                }
            }
            
            javaClass.addMethod(method);
            logger.debug("Converted method: {}", method.getName());
        }
    }
    
    private void addMainMethod(JavaClass javaClass) {
        JavaMethod mainMethod = new JavaMethod("main", "void");
        mainMethod.addParameter("String[] args");
        mainMethod.setVisibility("public static");
        
        mainMethod.addBodyLine(javaClass.getClassName() + " program = new " + 
            javaClass.getClassName() + "();");
        
        // Call the first method if any exist
        if (!javaClass.getMethods().isEmpty()) {
            String firstMethod = javaClass.getMethods().get(0).getName();
            mainMethod.addBodyLine("program." + firstMethod + "();");
        }
        
        javaClass.addMethod(mainMethod);
    }
    
    private String convertStatement(Statement statement) {
        switch (statement.getType()) {
            case DISPLAY:
                return convertDisplayStatement(statement);
            case MOVE:
                return convertMoveStatement(statement);
            case STOP:
                return "return;";
            case PERFORM:
                return convertPerformStatement(statement);
            case ADD:
                return convertAddStatement(statement);
            case SUBTRACT:
                return convertSubtractStatement(statement);
            case MULTIPLY:
                return convertMultiplyStatement(statement);
            case DIVIDE:
                return convertDivideStatement(statement);
            case COMPUTE:
                return convertComputeStatement(statement);
            case IF:
                return convertIfStatement(statement);
            case ACCEPT:
                return convertAcceptStatement(statement);
            default:
                return "// TODO: Convert " + statement.getType() + ": " + statement.getRawText();
        }
    }
    
    private String convertDisplayStatement(Statement statement) {
        String text = statement.getRawText();
        // Extract the display content
        String content = text.replaceFirst("(?i)DISPLAY\\s+", "").trim();
        content = content.replaceAll("\\.$", "");
        
        // Handle multiple items: DISPLAY 'Name: ' WS-NAME
        String[] items = content.split("\\s+");
        if (items.length > 1) {
            StringBuilder sb = new StringBuilder("System.out.print(");
            for (int i = 0; i < items.length; i++) {
                if (i > 0) sb.append(" + ");
                String item = items[i].trim();
                if (item.startsWith("'") || item.startsWith("\"")) {
                    sb.append(item);
                } else {
                    sb.append(convertToJavaFieldName(item));
                }
            }
            sb.append(");");
            return sb.toString();
        }
        
        // Single item
        if (content.startsWith("'") || content.startsWith("\"")) {
            return "System.out.println(" + content + ");";
        } else {
            return "System.out.println(" + convertToJavaFieldName(content) + ");";
        }
    }
    
    private String convertMoveStatement(Statement statement) {
        // Simplified MOVE conversion
        String text = statement.getRawText();
        // Pattern: MOVE source TO target
        String[] parts = text.split("(?i)\\s+TO\\s+");
        if (parts.length == 2) {
            String source = parts[0].replaceFirst("(?i)MOVE\\s+", "").trim();
            String target = parts[1].replaceAll("\\.$", "").trim();
            
            return convertToJavaFieldName(target) + " = " + 
                   (source.startsWith("'") || source.startsWith("\"") ? 
                    source : convertToJavaFieldName(source)) + ";";
        }
        return "// TODO: Convert MOVE: " + text;
    }
    
    private String convertPerformStatement(Statement statement) {
        String text = statement.getRawText();
        String paragraphName = text.replaceFirst("(?i)PERFORM\\s+", "").replaceAll("\\.$", "").trim();
        return convertToJavaMethodName(paragraphName) + "();";
    }
    
    private String mapCobolTypeToJava(DataItem item) {
        switch (item.getDataType()) {
            case ALPHANUMERIC:
            case ALPHABETIC:
                return "String";
            case NUMERIC:
                return "int";
            case DECIMAL:
                return "BigDecimal";
            default:
                return "Object";
        }
    }
    
    private String formatJavaValue(DataItem item) {
        String value = item.getValue();
        if (value == null) {
            return null;
        }
        
        switch (item.getDataType()) {
            case ALPHANUMERIC:
            case ALPHABETIC:
                return "\"" + value + "\"";
            case NUMERIC:
                return value;
            case DECIMAL:
                return "new BigDecimal(\"" + value + "\")";
            default:
                return "null";
        }
    }
    
    private String convertToJavaClassName(String cobolName) {
        // Convert COBOL-STYLE-NAME to JavaStyleName
        String[] parts = cobolName.split("-");
        StringBuilder sb = new StringBuilder();
        for (String part : parts) {
            sb.append(part.substring(0, 1).toUpperCase());
            sb.append(part.substring(1).toLowerCase());
        }
        return sb.toString();
    }
    
    private String convertToJavaFieldName(String cobolName) {
        // Convert WS-NAME to wsName
        String[] parts = cobolName.split("-");
        StringBuilder sb = new StringBuilder();
        sb.append(parts[0].toLowerCase());
        for (int i = 1; i < parts.length; i++) {
            sb.append(parts[i].substring(0, 1).toUpperCase());
            sb.append(parts[i].substring(1).toLowerCase());
        }
        return sb.toString();
    }
    
    private String convertToJavaMethodName(String cobolName) {
        // Convert PARAGRAPH-NAME to paragraphName
        return convertToJavaFieldName(cobolName);
    }
    
    /**
     * Convert COBOL ADD statement to Java.
     * Supports: ADD A TO B, ADD A B TO C, ADD A TO B GIVING C
     */
    private String convertAddStatement(Statement statement) {
        String text = statement.getRawText().trim();
        text = text.replaceFirst("(?i)^ADD\\s+", "").replaceAll("\\.$", "");
        
        // Handle GIVING clause: ADD A B TO C GIVING D
        if (text.toUpperCase().contains(" GIVING ")) {
            String[] parts = text.split("(?i)\\s+GIVING\\s+");
            String target = convertToJavaFieldName(parts[1].trim());
            String expression = parts[0].replaceAll("(?i)\\s+TO\\s+", " + ");
            expression = expression.replaceAll("\\s+", " + ");
            String[] operands = expression.split("\\s*\\+\\s*");
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < operands.length; i++) {
                if (i > 0) sb.append(" + ");
                sb.append(convertToJavaFieldName(operands[i].trim()));
            }
            return target + " = " + sb.toString() + ";";
        }
        
        // Handle TO clause: ADD A TO B (means B = B + A)
        if (text.toUpperCase().contains(" TO ")) {
            String[] parts = text.split("(?i)\\s+TO\\s+");
            String source = parts[0].trim();
            String target = convertToJavaFieldName(parts[1].trim());
            
            // Handle multiple sources: ADD A B TO C
            String[] sources = source.split("\\s+");
            if (sources.length > 1) {
                StringBuilder sb = new StringBuilder(target + " = " + target);
                for (String src : sources) {
                    sb.append(" + ").append(convertToJavaFieldName(src.trim()));
                }
                return sb.toString() + ";";
            } else {
                return target + " = " + target + " + " + convertToJavaFieldName(source) + ";";
            }
        }
        
        return "// TODO: Convert ADD: " + statement.getRawText();
    }
    
    /**
     * Convert COBOL SUBTRACT statement to Java.
     * Supports: SUBTRACT A FROM B, SUBTRACT A FROM B GIVING C
     */
    private String convertSubtractStatement(Statement statement) {
        String text = statement.getRawText().trim();
        text = text.replaceFirst("(?i)^SUBTRACT\\s+", "").replaceAll("\\.$", "");
        
        // Handle GIVING clause
        if (text.toUpperCase().contains(" GIVING ")) {
            String[] parts = text.split("(?i)\\s+GIVING\\s+");
            String target = convertToJavaFieldName(parts[1].trim());
            String[] operands = parts[0].split("(?i)\\s+FROM\\s+");
            String subtrahend = convertToJavaFieldName(operands[0].trim());
            String minuend = convertToJavaFieldName(operands[1].trim());
            return target + " = " + minuend + " - " + subtrahend + ";";
        }
        
        // Handle FROM clause: SUBTRACT A FROM B (means B = B - A)
        if (text.toUpperCase().contains(" FROM ")) {
            String[] parts = text.split("(?i)\\s+FROM\\s+");
            String source = convertToJavaFieldName(parts[0].trim());
            String target = convertToJavaFieldName(parts[1].trim());
            return target + " = " + target + " - " + source + ";";
        }
        
        return "// TODO: Convert SUBTRACT: " + statement.getRawText();
    }
    
    /**
     * Convert COBOL MULTIPLY statement to Java.
     * Supports: MULTIPLY A BY B, MULTIPLY A BY B GIVING C
     */
    private String convertMultiplyStatement(Statement statement) {
        String text = statement.getRawText().trim();
        text = text.replaceFirst("(?i)^MULTIPLY\\s+", "").replaceAll("\\.$", "");
        
        // Handle GIVING clause
        if (text.toUpperCase().contains(" GIVING ")) {
            String[] parts = text.split("(?i)\\s+GIVING\\s+");
            String target = convertToJavaFieldName(parts[1].trim());
            String[] operands = parts[0].split("(?i)\\s+BY\\s+");
            String multiplicand = convertToJavaFieldName(operands[0].trim());
            String multiplier = convertToJavaFieldName(operands[1].trim());
            return target + " = " + multiplicand + " * " + multiplier + ";";
        }
        
        // Handle BY clause: MULTIPLY A BY B (means B = B * A)
        if (text.toUpperCase().contains(" BY ")) {
            String[] parts = text.split("(?i)\\s+BY\\s+");
            String source = convertToJavaFieldName(parts[0].trim());
            String target = convertToJavaFieldName(parts[1].trim());
            return target + " = " + target + " * " + source + ";";
        }
        
        return "// TODO: Convert MULTIPLY: " + statement.getRawText();
    }
    
    /**
     * Convert COBOL DIVIDE statement to Java.
     * Supports: DIVIDE A INTO B, DIVIDE A BY B GIVING C
     */
    private String convertDivideStatement(Statement statement) {
        String text = statement.getRawText().trim();
        text = text.replaceFirst("(?i)^DIVIDE\\s+", "").replaceAll("\\.$", "");
        
        // Handle GIVING clause with BY
        if (text.toUpperCase().contains(" GIVING ") && text.toUpperCase().contains(" BY ")) {
            String[] parts = text.split("(?i)\\s+GIVING\\s+");
            String target = convertToJavaFieldName(parts[1].trim());
            String[] operands = parts[0].split("(?i)\\s+BY\\s+");
            String dividend = convertToJavaFieldName(operands[0].trim());
            String divisor = convertToJavaFieldName(operands[1].trim());
            return target + " = " + dividend + " / " + divisor + ";";
        }
        
        // Handle INTO clause: DIVIDE A INTO B (means B = B / A)
        if (text.toUpperCase().contains(" INTO ")) {
            String[] parts = text.split("(?i)\\s+INTO\\s+");
            String source = convertToJavaFieldName(parts[0].trim());
            String target = convertToJavaFieldName(parts[1].trim());
            return target + " = " + target + " / " + source + ";";
        }
        
        return "// TODO: Convert DIVIDE: " + statement.getRawText();
    }
    
    /**
     * Convert COBOL COMPUTE statement to Java.
     * Supports: COMPUTE A = B + C * D
     */
    private String convertComputeStatement(Statement statement) {
        String text = statement.getRawText().trim();
        text = text.replaceFirst("(?i)^COMPUTE\\s+", "").replaceAll("\\.$", "");
        
        // Split on = sign
        String[] parts = text.split("=");
        if (parts.length == 2) {
            String target = convertToJavaFieldName(parts[0].trim());
            String expression = parts[1].trim();
            
            // Convert COBOL operators to Java
            expression = expression.replaceAll("\\*\\*", "Math.pow"); // Exponentiation
            
            // Convert variable names in the expression
            String[] tokens = expression.split("([+\\-*/()\\s])");
            for (String token : tokens) {
                token = token.trim();
                if (!token.isEmpty() && !token.matches("[0-9.]+") && 
                    !token.equals("Math.pow")) {
                    expression = expression.replaceAll("\\b" + token + "\\b", 
                        convertToJavaFieldName(token));
                }
            }
            
            return target + " = " + expression + ";";
        }
        
        return "// TODO: Convert COMPUTE: " + statement.getRawText();
    }
    
    /**
     * Convert COBOL IF statement to Java.
     * Basic support for simple IF conditions.
     */
    private String convertIfStatement(Statement statement) {
        String text = statement.getRawText().trim();
        text = text.replaceFirst("(?i)^IF\\s+", "").replaceAll("\\.$", "");
        
        // Convert COBOL comparison operators to Java
        text = text.replaceAll("(?i)\\s+EQUAL\\s+TO\\s+", " == ");
        text = text.replaceAll("(?i)\\s+EQUALS\\s+", " == ");
        text = text.replaceAll("(?i)\\s+=\\s+", " == ");
        text = text.replaceAll("(?i)\\s+NOT\\s+EQUAL\\s+TO\\s+", " != ");
        text = text.replaceAll("(?i)\\s+GREATER\\s+THAN\\s+", " > ");
        text = text.replaceAll("(?i)\\s+LESS\\s+THAN\\s+", " < ");
        text = text.replaceAll("(?i)\\s+>=\\s+", " >= ");
        text = text.replaceAll("(?i)\\s+<=\\s+", " <= ");
        text = text.replaceAll("(?i)\\s+AND\\s+", " && ");
        text = text.replaceAll("(?i)\\s+OR\\s+", " || ");
        text = text.replaceAll("(?i)\\s+NOT\\s+", " ! ");
        
        // Convert variable names
        String[] tokens = text.split("([=!<>&|()\\s])");
        for (String token : tokens) {
            token = token.trim();
            if (!token.isEmpty() && !token.matches("[0-9.]+") && 
                !token.matches("[\"'].*[\"']")) {
                text = text.replaceAll("\\b" + token + "\\b", 
                    convertToJavaFieldName(token));
            }
        }
        
        return "if (" + text + ") {";
    }
    
    /**
     * Convert COBOL ACCEPT statement to Java.
     * Uses Scanner for console input.
     */
    private String convertAcceptStatement(Statement statement) {
        String text = statement.getRawText().trim();
        String variable = text.replaceFirst("(?i)^ACCEPT\\s+", "").replaceAll("\\.$", "").trim();
        String javaVar = convertToJavaFieldName(variable);
        
        return "// TODO: Implement input for " + javaVar + " using Scanner";
    }
}

// Made with Bob
